name: Unit tests

on:
    push:
        branches: 
            - '1-creation-compte-form-frontend'

jobs:
    tests:
        runs-on: windows-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Setup Node
            uses: actions/setup-node@v2
            with:
                node-version: 18.x
          - name: Install dependencies
            run: npm ci
          - name: Testing...
            run: npm test
            
