name: Unit tests

on:
    push:
        branches: 
            - '1-creation-compte-form-frontend'

jobs:
    tests:
        runs-on: windows-latest
        steps:
          - name: Hello step
            run: echo "Hello world"